name: Test Ticked Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Python 3.13
      run: brew install python@3.13

    - name: Install build dependencies
      run: |
        python3.13 -m pip install --upgrade pip
        python3.13 -m pip install wheel setuptools

    - name: Run formula tests
      run: |
        mkdir -p Formula
        cp ticked.rb Formula/
        ruby test_formula.rb

    - name: Test installation
      run: |
        brew install --build-from-source ./Formula/ticked.rb
        brew test ./Formula/ticked.rb
        ticked --version

    - name: Test all imports
      run: |
        python3.13 -c "
        import certifi
        import textual
        import textual_dev
        import rich
        import psutil
        import pygments
        import pyfiglet
        import spotipy
        import dotenv
        import typing_extensions
        import platformdirs
        import requests
        import urllib3
        import idna
        import redis
        import xdg_base_dirs
        import syntax
        import caldav
        import lxml
        import icalendar
        import vobject
        print('All imports successful')
        "